name: Test React App
on: push
jobs:
    runs-on: ubuntu-latest
    steps:
        - name: Get repository code
          uses: actions/checkout@4
        - name: Install dependencies
          run: npm ci
        - name: Test app
          run: npm run test